global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'frontend'
    static_configs:
      - targets: ['app:8000']
  - job_name: 'backend'
    static_configs:
      - targets: ['model-service:5000']
